quarkus.application.name=swift-bank-api
quarkus.application.version=v1

quarkus.http.port=8080
quarkus.http.host=0.0.0.0

quarkus.jackson.write-dates-as-timestamps=false
quarkus.jackson.fail-on-empty-beans=false

quarkus.log.level=INFO
quarkus.log.category."swift-bank-api".level=DEBUG
quarkus.banner.enabled=true
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n


